class CopykittenError(Exception): ...


def copy(content: str) -> None: ...
def copy_wait(_content: str) -> None: ...
def paste() -> str: ...
def clear() -> None:...
def copy_image(content: bytes, width: int, height: int) -> None: ...
def copy_image_wait(_content: bytes, _width: int, _height: int) -> None: ...
def paste_image() -> tuple[bytes, int, int]: ...
