class CopykittenError(Exception): ...


def copy(content: str) -> None: ...
def copy_wait(content: str) -> None: ...
def paste() -> str: ...
def clear() -> None:...
def copy_image(content: bytes, width: int, height: int) -> None: ...
def copy_image_wait(content: bytes, width: int, height: int) -> None: ...
def copy_file_list(file_list: list[str]) -> None: ...
def copy_file_list_wait(file_list: list[str]) -> None: ...
def paste_image() -> tuple[bytes, int, int]: ...
def paste_file_list() -> list[str]: ...
