name: CI

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    env:
      DISPLAY: :0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install test dependencies
        run:  sudo apt-get update & sudo apt-get install -y xvfb xsel
      - name: Run virtual X11 server
        run: Xvfb :0 -screen 0 800x600x16 &
      - name: Setup venv
        run: python -m venv .venv
      - name: Build extension module and install package
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          target: ${{ matrix.target }}
      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m unittest -v
#
#  windows:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.8'
#      - name: Build wheels
#        uses: PyO3/maturin-action@v1
#        with:
#          target: x64
#          args: --release --out dist --find-interpreter
#          sccache: 'true'
#      - name: Upload wheels
#        uses: actions/upload-artifact@v3
#        with:
#          name: wheels
#          path: dist
#
#  macos:
#    runs-on: macos-latest
#    strategy:
#      matrix:
#        target: [x86_64, aarch64]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.8'
#      - name: Build wheels
#        uses: PyO3/maturin-action@v1
#        with:
#          target: ${{ matrix.target }}
#          args: --release --out dist --find-interpreter
#          sccache: 'true'
#      - name: Upload wheels
#        uses: actions/upload-artifact@v3
#        with:
#          name: wheels
#          path: dist
